trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install Node Dependencies'

- script: |
    npx webdriver-manager update
  displayName: 'Update Webdrivers'

- script: |
    npm test
  displayName: 'Run Testcafe Tests'

#- task: PublishTestResults@2
#  inputs:
#    testResultsFormat: 'JUnit'
#    testResultsFiles: 'allure-results/*.xml'
#    testRunTitle: 'Protractor-Jasmine Execution Report'